language: generic
sudo: required # need super user to build
services:
    - docker # will require docker
before_install:
    - docker build -f Dockerfile.dev -t hoesslj/docker-react .

script:
    - docker run -e CI=true hoesslj/docker-react  npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-udemy"
    env: "DockerReactUdemy-env"
    bucket_name: "elasticbeanstalk-us-east-2-077844377417" 
    bucket_path: "docker-react-udemy"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
